// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SMS.Data;
using System;

namespace SMS.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20171121091334_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SMS.Models.Class", b =>
                {
                    b.Property<string>("ClassID");

                    b.Property<string>("ClassName");

                    b.Property<int>("NoOfStudents");

                    b.Property<int>("Year");

                    b.HasKey("ClassID");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("SMS.Models.Enrolled", b =>
                {
                    b.Property<int>("EnrolmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Marks");

                    b.Property<int>("StudentID");

                    b.Property<string>("SubjectID");

                    b.HasKey("EnrolmentID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Enrolled");
                });

            modelBuilder.Entity("SMS.Models.Student", b =>
                {
                    b.Property<int>("StudentID");

                    b.Property<string>("Address");

                    b.Property<string>("ClassID");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName");

                    b.Property<string>("GuardianName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("RegistrationDate");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SMS.Models.Subject", b =>
                {
                    b.Property<string>("SubjectID");

                    b.Property<string>("SubjectName");

                    b.HasKey("SubjectID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SMS.Models.Enrolled", b =>
                {
                    b.HasOne("SMS.Models.Student", "Student")
                        .WithMany("Enrolled")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SMS.Models.Subject", "Subject")
                        .WithMany("Enrolled")
                        .HasForeignKey("SubjectID");
                });

            modelBuilder.Entity("SMS.Models.Student", b =>
                {
                    b.HasOne("SMS.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID");
                });
#pragma warning restore 612, 618
        }
    }
}
